#!/bin/bash

tmpfile=`mktemp`
task=$2

declare -A testCount
declare -A timeLimit

while read i; do
	first=`echo $i | awk '{print \$1}'`
	second=`echo $i | awk '{print \$2}'`
	testCount[$first]=$second
done < checkers/settings/test_count;

while read i; do
	first=`echo $i | awk '{print \$1}'`
	second=`echo $i | awk '{print \$2}'`
	timeLimit[$first]=$second
done < checkers/settings/time_limit;

maxPoints=${testCount[$task]}
currentPoints=$maxPoints

function fail_timeout {
	echo "Timeout"
	currentPoints=$((currentPoints-1))
}

function fail_wrong {
	echo "Wrong answer"
	currentPoints=$((currentPoints-1))
}

for number in `seq 1 $maxPoints`
do
	echo "==== Test $number ===="
	if timeout ${timeLimit[$task]} $1 < checkers/tests/$task/$number.in > $tmpfile
	then
		diff -qb checkers/tests/$task/$number.out $tmpfile > /dev/null || fail_wrong
	else
		fail_timeout
	fi
done;

echo "<h2> Result: $currentPoints/$maxPoints </h2>"

# The line after __SSCK_RES_PACK__ is the actual score showed on the results
echo "__SSCK_RES_PACK__"
echo "$currentPoints"
