#!/bin/env bash

safeBin="LD_PRELOAD=./EasySandbox.so $1"
#safeBin="$1"
task=$2

declare -A timeLimit

while read i; do
	name=`echo $i | awk '{print \$1}'`
	limit=`echo $i | awk '{print \$2}'`
	timeLimit[$name]=$limit
done < checkers/settings/time_limit;

[ ${timeLimit[$task]+abc} ] || (echo "Internal system error. Please refresh the main submission page. (Missing time limit info)" && exit 1)
if [[ $? == 1 ]]; then exit 1; fi


groupSize=1
while read i; do
	name=`echo $i | awk '{print \$1}'`
	gtype=`echo $i | awk '{print \$2}'`
	if [[ "$gtype" == "simple" ]]
	then
		groupSize=`echo $i | awk '{print \$3}'`
		if [[ "$name" != "$task" ]]
		then
			groupSize=1
		fi
	else
		echo "Internal system error. Please refresh the main submission page. (Wrong grouping configuration)" && exit 1
	fi
done < checkers/settings/grouping;

correctGroups=0

currGroup=1
currTestInGroup=1
failsInCurrGroup=0

tmpfile=`mktemp`
sstmp=`mktemp` # system status tmp file
excode=`mktemp` # system status tmp file

function fixGroups {
	if (( $currTestInGroup == $groupSize ))
	then
		if (( $failsInCurrGroup == 0 ))
		then
			correctGroups=$((correctGroups+1))
		fi
		if (( $groupSize != 1 ))
		then
			echo "-----------------------------"
		fi
		currTestInGroup=1
		failsInCurrGroup=0
		currGroup=$((currGroup+1))
	else
		currTestInGroup=$((currTestInGroup+1))
	fi
}

function shortName {
	echo "$1" | awk -F '.' '{print $2}'
}

function fail_timeout {
	t=`shortName $1`
	echo -n "$t: <font color=\"fireBrick\">TIML</font>"
	failsInCurrGroup=$((failsInCurrGroup+1))
}

function fail_nonZeroExitCode {
	t=`shortName $1`
	echo -n "$t: <font color=\"brown\">CRSH</font>"
	failsInCurrGroup=$((failsInCurrGroup+1))
}

function fail_wrong {
	t=`shortName $1`
	echo -n "$t: <font color=\"darkRed\">WANS</font>"
	failsInCurrGroup=$((failsInCurrGroup+1))
}

function prn_ok {
	t=`shortName $1`
	echo -n "$t: <font color=\"green\">OK</font> ~$(<$sstmp)s."
}

for test in checkers/tests/$task/tests/*.in
do
	str="$test"
	if [[ ! $str =~ "00.in" ]]
	then
		out=`basename -s .in $test`.sol
		if timeout ${timeLimit[$task]} sh -c \
			"TIMEFORMAT=%3R; time ($safeBin < $test &> $tmpfile; echo \$? > $excode) &> $sstmp"
		then
			sed -i 1,2d $tmpfile # EasySandbox garbage, rtfm
			ec=$(<$excode)
			if [[ "$ec" == "0" ]]
			then
				(diff -qb checkers/tests/$task/tests/$out $tmpfile > /dev/null && prn_ok $out) \
					|| fail_wrong $out
			else
				fail_nonZeroExitCode $out
			fi
		else
			fail_timeout $out
		fi
		echo ""
		fixGroups
	fi
done;

currGroup=$((currGroup-1))
output=`python -c "print(round(100 / $currGroup * $correctGroups))"`
printf "<b>%d/%d</b>\n" $correctGroups $currGroup

# The line after __SSCK_RES_PACK__ is the actual score showed on the results
echo "__SSCK_RES_PACK__"
echo $output

rm $tmpfile
rm $sstmp
