#!/bin/bash

tmpfile=`mktemp`
task=$2

declare -A timeLimit

while read i; do
	first=`echo $i | awk '{print \$1}'`
	second=`echo $i | awk '{print \$2}'`
	timeLimit[$first]=$second
done < checkers/settings/time_limit;

maxPoints=0
fails=0

function fail_timeout {
	echo "Timeout"
	fails=$((fails+1))
}

function fail_wrong {
	echo "Wrong answer"
	fails=$((fails+1))
}

for test in checkers/tests/$task/tests/*.in
do
	echo "==== `basename $test` ===="

	str="`basename -s .in $test`"
	if [[ ! $str =~ ".00" ]]
	then
		maxPoints=$((maxPoints+1))
		if timeout ${timeLimit[$task]} $1 < $test > $tmpfile
		then
			out=`basename -s .in $test`.sol
			diff -qb checkers/tests/$task/tests/$out $tmpfile > /dev/null || fail_wrong
		else
			fail_timeout
		fi
	else
		echo "Probably a test case. Ignoring..."
	fi
done;

succsessful=$((maxPoints-$fails))
output=`python -c "print(round(100 / $maxPoints * $succsessful))"`
printf "<h2> Result: %d - %d/%d <h2>\n" $output $succsessful $maxPoints

# The line after __SSCK_RES_PACK__ is the actual score showed on the results
echo "__SSCK_RES_PACK__"
echo $output
